inherit_gem:
  dc-rubocop: default.yml

AllCops:
  TargetRubyVersion: 2.6

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
