#!/usr/bin/ruby
# frozen_string_literal: true

require "rblox"

# TODO: use optparse

abort("usage blah") if ARGV.size > 1
l = RbLox::Interpreter.new
if ARGV.size == 1
  l.read_source_file(ARGV[0])
else
  l.run_prompt
end
